name: Hello World!

on: push

jobs:
  hello_world_job:    
      runs-on: ubuntu-latest
      steps: 
      - name: step1
        run: echo "Hello, World!"
      - name: step2
        run: date
      - name: step3
        run: ls -l
      
