name: Hello World!

on: push

jobs:
  hello_world_job:    
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
          run: echo Hello, world!
             run:|
              date
              ls-l
