name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
      - uses: rtCamp/action-slack-notify@v2
       
    env:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      SLACK_TITLE: Post Title
      COMMIT_MESSAGES: ${{ contains(join(github.event.commits.*.message),'skip') }}
      
      
      run: echo "$COMMIT_MESSAGES"
