# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
 
    runs-on: ubuntu-latest

    steps:
       - uses: jtalk/url-health-check-action@v1.2
         with:
           url: https://testing_protected-reaches-72080.herokuapp.com/
