name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: 8398a7/action-slack@v3
        with:
           status: ${{ job.status }}
           fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message
       
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      COMMIT_MESSAGES: ${{ contains(join(github.event.commits.*.message),'skip') }}
      
      
      run: echo "$COMMIT_MESSAGES"
