name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job_skip:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ join(github.event.commits.*.message) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ contains(join(github.event.commits.*.message),'skip') }}
        run: echo "$COMMIT_MESSAGES"
